# -*- coding: utf-8 -*-
"""CNN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ak9-fOKuLXX8LdMFrRq_e9N_yVOY209d
"""

pip install tensorflow

import tensorflow as tf
print(tf.__version__)

from tensorflow import keras

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

fashion_data = keras.datasets.fashion_mnist.load_data()

print(fashion_data)

from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

print(confusion_matrix)

(x_train_sp, y_train_sp), (x_test_sp, y_test_sp) = fashion_data

items_name = ["T-shirt/top", "Trouser", "Pullover","Dress", "Coat","Sandal", "Shirt","Sneaker", "Bag", "Ankle boot"]



#reshaping data
x_train_sp = x_train_sp.reshape((60000, 28,28,1))
x_test_sp = x_test_sp.reshape((10000, 28,28,1))
x_train_sp.shape

#normalizing data
x_train_norm = x_train_sp/255
x_test_norm = x_test_sp/255

x_validate, x_train = x_train_norm[:5000], x_train_norm[5000:]
y_validate, y_train = y_train_sp[:5000], y_train_sp[5000:]

tf.random.set_seed(42)
model = keras.models.Sequential()
model.add(keras.layers.Conv2d(filter=32, kernal_size=(3,3), strides=1, padding="valid", activation="relu", input_shape=(28,28,1)))
model.add(keras.layers.Maxpolling2D((2,2)))
model.add(keras.layers.Flatten())

