# -*- coding: utf-8 -*-
"""Copy of Tensor flow basics.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CKAmGN_S_q4ai2k_FxgJ_bdMtf5qsWg_

# Introduction to tensor flow
"""

import tensorflow as tf

tf.__version__

"""# Creating variables and constants in tensor"""

constant_tf=tf.constant([[1,2],[3,4]])

constant_tf

variable_tf=tf.Variable([[5,6],[1,3]])

variable_tf

"""#Tensor Transpose"""

transpose_tf=tf.transpose(constant_tf)

transpose_tf

"""#Multiplication in tf"""

multipl_mat=tf.matmul(constant_tf,transpose_tf)

multipl_mat

multipl_mat2=tf.multiply(constant_tf,transpose_tf)

multipl_mat2

tensor_transpose_float=tf.cast(constant_tf,tf.float32)

determinant=tf.linalg.det(tensor_transpose_float)

determinant

inver = tf.linalg.inv(tensor_transpose_float)

inver

"""# Creating ZEROS and ONES tensor"""

ZERO_TSR=tf.zeros(shape=[2,3],dtype=tf.int32)

ZERO_TSR

ONES_TSR = tf.ones(shape=[2,3],dtype=tf.float32)



import numpy as np

iris_data = np.array([[1, 3, 4, 6],[2, 5, 7, 1]])

tf.convert_to_tensor(iris_data)

