# -*- coding: utf-8 -*-
"""keras_basics.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NrV4mt9O1d2aBqX6my-P_SUh0Hqw1PCm
"""

import tensorflow as tf
import numpy as np

from tensorflow import keras
import matplotlib
from matplotlib import pyplot as pt

tf.keras.datasets

from keras.datasets import cifar10

d1 = cifar10.load_data()

d1



(trainx, trainy),(testx, testy)=cifar10.load_data()

testy

pt.imshow(trainx[72])
pt.show()

from keras.datasets import fashion_mnist

(trainx, trainy),(testx, testy)=fashion_mnist.load_data()

trainx.shape

pt.imshow(trainx[7020])
pt.show()

text_data = np.array([["hi"], ["hello hemanth"]])
text_data

from tensorflow.keras.layers import TextVectorization

vectorizer = TextVectorization(output_mode="int")

vectorizer.adapt(text_data)

vector_data = vectorizer(text_data)

vector_data

vectorizer.get_vecabulary()

