# -*- coding: utf-8 -*-
"""simple_generetive_AI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KSi1Rf2iItaihOrGctSXv8jUqLaFNkn4
"""

pip install tensorflow-hub

from matplotlib import gridspec
import matplotlib.pyplot as plt
import numpy as np
import tensorflow as tf
import tensorflow_hub as tf_hub
import PIL
from google.colab import files

"""# Image Processing Function"""

def load_image(image, image_size=(512,512)):
  img = tf.io.read_file(image)
  img = tf.image.decode_image(img, channels=3)
  img = tf.image.convert_image_dtype(img, tf.float32)
  img= tf.image.resize(img, image_size,preserve_aspect_ratio=True)
  img=img[tf.newaxis, :]
  return img

upload_image = files.upload()

orginal_image = load_image("O_I_AI_T (2).jpg")

orginal_image



upload = files.upload()

style_image = load_image("zebra-1-1-sq (1).jpg")

"""# Dispaly Function"""

def imshow(img, title=None):
  if len(img.shape) > 3:
    img = tf.squeeze(img, axis=0)
  plt.imshow(img)
  if title:
    plt.title(title)

"""# Displaying Image"""

imshow(orginal_image)

imshow( style_image)

"""# Hub Handle"""

hub_handle = 'https://tfhub.dev/google/magenta/arbitrary-image-stylization-v1-256/2'

"""# Hub Module"""

hub_module = tf_hub.load(hub_handle)

"""# Neural Style Transfer"""

outputs = hub_module(orginal_image, style_image)

outputs

"""#Displaying Styled Image"""

plt.subplot(1,2,1)
imshow(orginal_image)
plt.subplot(1,2,2)
imshow(outputs[0])



"""#Assingment Part_ROI(Region of interest)"""





pip install tensorflow-hub

pip install tensorflow tensorflow_hub matplotlib pillow opencv-python

pip install tensorflow

import tensorflow as tf
import tensorflow_datasets as tfds
import tensorflow_hub as hub
import numpy as np
import matplotlib.pyplot as plt
from PIL import Image
import cv2
from google.colab import files

# Upload images
from google.colab import files
uploaded = files.upload()

# Load images
original_image = load_image("close-up-portrait-of-smiling-handsome-young-caucasian-man-face-looking-at-camera-on-isolated-light-gray-studio-background-photo (3).jpg")

uploaded = files.upload()

style_image = load_image("360_F_632906383_JHVerN4XvhucoNfuMnCBXgAV7oaymQGp (4).jpg")

# Load style transfer model
style_model = hub.load('https://tfhub.dev/google/magenta/arbitrary-image-stylization-v1-256/2')
stylized_image = style_model(tf.expand_dims(original_image, 0), tf.expand_dims(style_image, 0))[0][0]

original_image = load_image("close-up-portrait-of-smiling-handsome-young-caucasian-man-face-looking-at-camera-on-isolated-light-gray-studio-background-photo (2).jpg")

upload = files.upload()

style_image = load_image("360_F_632906383_JHVerN4XvhucoNfuMnCBXgAV7oaymQGp (2).jpg")

# Load style transfer model
style_model = hub.load('https://tfhub.dev/google/magenta/arbitrary-image-stylization-v1-256/2')
stylized_image = style_model(tf.expand_dims(original_image, 0), tf.expand_dims(style_image, 0))[0][0]

# Segmentation Function
def segment_image(image_tensor):
    model = hub.load("https://tfhub.dev/tensorflow/mask_rcnn/inception_resnet_v2_1024x1024/1.")

    resized_image = tf.image.resize(image_tensor, [513, 513])
    resized_image = tf.cast(resized_image, tf.uint8)
    batched = tf.expand_dims(resized_image, axis=0)

    result = model(batched)
    mask = result['semantic_pred'][0]
    mask_resized = tf.image.resize(tf.expand_dims(mask, -1), tf.shape(image_tensor)[0:2], method='nearest')
    binary_mask = tf.cast(mask_resized > 0, tf.float32)

    return binary_mask

# Apply segmentation mask
object_mask = segment_image(original_image)

# Blend stylized and original image using mask
blended = object_mask * stylized_image + (1 - object_mask) * original_image



