# -*- coding: utf-8 -*-
"""Single Layer perceptron.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tY_EnGRyiNYbj7np-0Qz3yxweHAZZNnl
"""

x = iris.data[:, (2,3)]
y = (iris.target  == 0).astype(int)

x

y

"""Applying the model"""

ptron = Perceptron(random_state = 42)



ptron.fit(x,y)

"""Predicting using model"""

y_pred = ptron.predict(x)

print(y_pred)

print(y == y_pred)

len(y)

len(y_pred)

print(f"Accuracy Score : {accuracy_score(y, y_pred)}")

"""Coefficient values from model"""

print(f"coefficient or Weight: {ptron.coef_}")

"""Weights assingned to the features

Intercept value from model
"""

print(f"Intercept or bios : {ptron.intercept_}")

